# Documentação
# Desabilita a interface visual do Swagger UI
springdoc.swagger-ui.enabled=false

# Desabilita o endpoint que gera o JSON/YAML da especificação (v3/api-docs)
springdoc.api-docs.enabled=false