spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?createDatabaseIfNotExist=true

# Documentação
# Desabilita a interface visual do Swagger UI
springdoc.swagger-ui.enabled=true

# Desabilita o endpoint que gera o JSON/YAML da especificação (v3/api-docs)
springdoc.api-docs.enabled=true